#pragma once
// Auto-generated by the Druid editor — safe to edit below the stubs.
#include <druid.h>

#ifdef __cplusplus
extern "C" {
#endif

#define GUN_FIELDS(FIELD) \
    FIELD(GUN_POSITION_X, "PositionX", f32, HOT) \
    FIELD(GUN_POSITION_Y, "PositionY", f32, HOT) \
    FIELD(GUN_POSITION_Z, "PositionZ", f32, HOT) \
    FIELD(GUN_ROTATION, "Rotation", Vec4, HOT) \
    FIELD(GUN_SCALE, "Scale", Vec3, HOT) \
    FIELD(GUN_COOLDOWN, "COOLDOWN", f32, COLD) \
    FIELD(GUN_AMMO, "AMMO", u32, COLD) \
    FIELD(GUN_RELOAD, "RELOAD", f32, COLD) \
    FIELD(GUN_SPEED, "SPEED", f32, COLD) \
    FIELD(GUN_SPREAD_MAX, "SPREAD_MAX", f32, COLD) \
    FIELD(GUN_SPREAD_RATE, "SPREAD_RATE", f32, COLD) \
    FIELD(GUN_SPREAD_DECAY, "SPREAD_DECAY", f32, COLD) \
    FIELD(GUN_RECOIL, "RECOIL", f32, COLD) \
    FIELD(GUN_RECOIL_FIRST, "RECOIL_FIRST", f32, COLD)

DECLARE_ARCHETYPE(Gun, GUN_FIELDS)

DSAPI void spawnGunInArch;
DSAPI void gunInit(void);
DSAPI void gunUpdate(Archetype *arch, f32 dt);
DSAPI void gunRender(Archetype *arch, Renderer *r);
DSAPI void gunDestroy(void);

DSAPI void druidGetECSSystem_Gun(ECSSystemPlugin *out);

#ifdef __cplusplus
}
#endif
